### ISSUE TITLE
[Commissioning] Save default gateway address

### ISSUE THREAD

**Issue by ltukezl** [openthread/openthread#2150] opened 2017-08-29 09:05 UTC
When using wpantund and having programmed the nfc meshcop example from Nordics infocenter, I next use the command ```wpanctl config-gateway fefe:fefe:fefe:fefe:: -d``` to give a default prefix to my devices.  
  
  However the problem is, that once I lose the power of the device, I am unable to have the old address info, without reverting to the non gateway address. Only way to attain new address is to factory reset and repairing the device.

**Comment by jwhui** [comment] 2017-09-18 20:28
Closing as duplicate of https://github.com/openthread/borderrouter/issues/104.

**Closed by jwhui** 2017-09-18 20:28 UTC
