### ISSUE TITLE
otThreadGetPSKc and otThreadSetPSKc

### ISSUE THREAD

**Issue by thcu-gp** [openthread/openthread#1781] opened 2017-05-17 12:15 UTC
Currently `otThreadGetPSKc` and `otThreadSetPSKc` they are located in `src/core/api/thread_api.cpp`. However the are enclosed by `#if OPENTHREAD_FTD ... #endif`
Shouldn't they be moved to `src/core/api/thread_ftd_api.cpp`

**Comment by chshu** [comment] 2017-05-17 13:21
@thcu-gp, Thanks for pointing it out, I think it is caused by a carelessness rebase operation: When I was working on #1680 (Remove some Leader/Router related features from MTD build), the PR #1635 (Add PSKc API) has not been merged yet. And after #1635 is merged, the rebase operation didn't complain any conflicts, so I ignored these two functions.

I have pushed #1782 to address this issue, thanks.

**Closed** 2017-05-19 03:52 UTC
