### ISSUE TITLE
[posix-app] dynamic radio log level support

### ISSUE THREAD

**Issue by bukepo** [openthread/openthread#3649] opened 2019-03-06 03:18 UTC
**Is your feature request related to a problem? Please describe.**
logging

**Describe the solution you'd like**
add an argument to posix-app to support setting logging level of radio chip.

**Describe alternatives you've considered**
also provide a platform-specific API to set this dynamically.

**Additional context**
It's helpful when debugging.

**Comment by jwhui** [comment] 2022-12-07 20:11
Duplicate of #4346

**Closed by jwhui** 2022-12-07 20:11 UTC
Labels: enhancement, P4, platform: posix
