### ISSUE TITLE
Upgarde the Openthread Version of REED K32W End device

### ISSUE THREAD

**Issue by dipVyas92** [openthread/openthread#8997] opened 2023-04-27 07:17 UTC
Hi,

We used a hybrid REED device example of **NXP SDK version 2.6.4** to develop one custom application. Now we want an upgrade the REED End device's Openthread version from **1.1 to 1.3**.

If we use SDK v2.6.9, then we fulfill this requirement? Or is there any other way to upgrade Opthread version?

How to check the Openthred version in SDK?

**Can anyone help me to understand this?**

**Comment by jwhui** [comment] 2023-05-03 19:53
Duplicate of https://github.com/openthread/ot-nxp/issues/488

**Closed by jwhui** 2023-05-03 19:53 UTC
