### ISSUE TITLE
The otbr-agent does not respond to ot-ctl command and restful request(localhost:8081/diagnostics), it seems that the main thread of otbr-agent entered an endless loop.

### ISSUE THREAD

**Issue by jinpeng1989** [openthread/openthread#8527] opened 2022-12-14 03:05 UTC
The otbr-agent does not respond to ot-ctl command and restful request(localhost:8081/diagnostics), can respond for ubus. It seems that the main thread of otbr-agent entered an endless loop. 

The uptime of this OTBR device is 2 day, the problem appeared after the device had been running for a day, do not recover now. 

Build steps
There are 100 devices in this system, 1 OTBR + 15 REED + 85 SED.
Network topology
![image](https://user-images.githubusercontent.com/97089879/207491502-208c4bc9-9ee0-4922-bc6a-fec75db7b711.png)
syslog for otbr-agent

The issue is difficult to reproduce. What other information can help locate the issue? 
[syslog_otbr-agent.log](https://github.com/openthread/openthread/files/10223937/syslog_otbr-agent.log)

**Comment by jinpeng1989** [comment] 2022-12-14 03:18
Is there a mechanism to monitor threads entering an endless loop?

**Comment by jwhui** [comment] 2022-12-14 03:36
This appears to be a duplicate of #8510 .

**Comment by jwhui** [comment] 2023-02-13 19:37
Closing stale issue.

**Closed by jwhui** 2023-02-13 19:37 UTC
