### ISSUE TITLE
When DHCPv6 is enabled for the thread network, the IPv6 prefix shall be configurable (such as for 96, 104, 120)

### ISSUE THREAD

**Issue by HeroHerbert** [openthread/openthread#7014] opened 2021-09-16 09:17 UTC
The thread Child Can't get IPv6 address from the router with both DHCP server/client enabled when the prefix length is bigger than 64. (When the prefix is 64, the IPv6 address can be assigned).

process:
ot-ctl netdata publish prefix fd11:96::/96 pdros med
ot-ctl netdata show (display what is configured at both child and leader devices)
ot-ctl ipaddr

The syslog shows that the client had sent out DHCPv6 solicit packet, and the server has already replied that packet, yet the ipv6 address is not there.
Please help to resolve .

This is very important for NAT64 application, we want to allocate ipaddress in some thread network to be of the form
fd11:22::c0a8:0500/120, so it can easily be used in IPV4/V6 interworking place with a simple Stateless NAT64 server.

**Comment by jwhui** [comment] 2021-09-23 15:59
This appears to be a duplicate of #7013.

**Closed by jwhui** 2021-09-23 15:59 UTC
Labels: duplicate, question
