### ISSUE TITLE
Implement dataset storage feature

### ISSUE THREAD

**Issue by chshu** [openthread/openthread#837] opened 2016-10-18 10:49 UTC
Thread devices need to store active operational dataset and pending operational dataset on non-volatile memory properly, and could retrieve them after hardware reset.

**Comment by jwhui** [comment] 2016-10-18 20:54
Is this a duplicate of #432?

**Comment by chshu** [comment] 2016-10-18 22:53
Yes, it is duplicate, I have closed #432 , and will go on with this one.

**Closed** 2016-10-25 05:13 UTC
Labels: enhancement, P1
