### ISSUE TITLE
Get the hardware mac

### ISSUE THREAD

**Issue by NOA-Ben** [openthread/openthread#3188] opened 2018-10-22 03:23 UTC
I can get the unique identifier of the device through the API interface. I need to use 3 or more slave nodes. Each slave node has a temperature sensor and transmits the temperature to the root node. I need to identify which temperature value comes from. node

**Comment by jwhui** [comment] 2018-10-22 22:01
Duplicate of #3187.

**Closed by jwhui** 2018-10-22 22:01 UTC
Labels: question
