### ISSUE TITLE
Thread Device's Channel, PAN ID, XPAN ID, and Network Name 

### ISSUE THREAD

**Issue by OlivierGre** [openthread/openthread#7855] opened 2022-06-30 09:05 UTC
Hi,
In Thread's documentation, it is written this ([link](https://openthread.io/guides/thread-primer/network-discovery#join_an_existing_network)):

> If the device elects to join an existing network, it configures its Channel, PAN ID, XPAN ID, and Network Name to match that of the target network via Thread Commissioning, then goes through the MLE Attach process to attach as a Child (End Device). This process is used for Child-Parent links.

I'm wondering if we are doing it right because, in our implementation, we are setting those parameters of the Thread device (Channel, PAN ID, XPAN ID, and Network Name) BEFORE doing the commissioning (we set them to match the ones of the OTBR).
Is it normal to hardcode this information or shall we retrieve it during the commissioning?

How shall it work in a commercial product?
Let's say that we have a Thread network at home and that we buy a new Thread device. How will the Thread device get the parameters (Channel, PAN ID, XPAN ID, and Network Name) to use?

Thank you

**Comment by jwhui** [comment] 2022-06-30 12:33
Duplicate of:
* #7854

**Closed by jwhui** 2022-06-30 12:33 UTC
Labels: duplicate
