### ISSUE TITLE
how to send and receive ipv6 packet throw thread protocol with nrf52840

### ISSUE THREAD

**Issue by testter2** [openthread/openthread#3599] opened 2019-02-17 00:56 UTC
I'm working on a project with nrf52840 and i'm trying to send and receive ipv6 packet throw thread protocol so i tried to use to send with otIp6Send and receive with otIp6SetReceiveCallback but code doesn't see the function that i pass to otIp6SetReceiveCallback so i don't can't receive from transmitter.

i also tried to handle testing example(packet_error_rate) in nRF5SDKforThreadv 0.11 sdk which sends udp packets  so i can remove udp layer  and work with ip6 functions of openthread but i stuck in the same problem.

 
questions :
are there any clear steps to send and receive ip6 packets over thread and what needs to be initialized ?
any clear example that sends and receive ip6 packets over thread ?

**Comment by jwhui** [comment] 2019-02-18 04:34
Can you clarify what you mean by: "code doesn't see the function that i pass to otIp6SetReceiveCallback"?

**Comment by testter2** [comment] 2019-02-19 15:18
i'm working on thread_simple_coap example from nordic with some changes
in server side : we added case for button 2 to set new receiving callback function when receiving  an ipv6 packet. and at this function we print received packet.
in client side : we added case for button 2 to send ipv6 with otIp6Send function after we getting addresses from provisioning_response_handler function and construct header as mentioned before

main at server side (receiver)

```
/**
 * Copyright (c) 2017 - 2017, Nordic Semiconductor ASA
 * 
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 
 * 2. Redistributions in binary form, except as embedded into a Nordic
 *    Semiconductor ASA integrated circuit in a product or a software update for
 *    such product, must reproduce the above copyright notice, this list of
 *    conditions and the following disclaimer in the documentation and/or other
 *    materials provided with the distribution.
 * 
 * 3. Neither the name of Nordic Semiconductor ASA nor the names of its
 *    contributors may be used to endorse or promote products derived from this
 *    software without specific prior written permission.
 * 
 * 4. This software, with or without modification, must only be used with a
 *    Nordic Semiconductor ASA integrated circuit.
 * 
 * 5. Any software provided in binary form under this license must not be reverse
 *    engineered, decompiled, modified and/or disassembled.
 * 
 * THIS SOFTWARE IS PROVIDED BY NORDIC SEMICONDUCTOR ASA "AS IS" AND ANY EXPRESS
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY, NONINFRINGEMENT, AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL NORDIC SEMICONDUCTOR ASA OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * 
 */
/** @file
 *
 * @defgroup simple_coap_server_example_main main.c
 * @{
 * @ingroup simple_coap_server_example_example
 * @brief Simple CoAP Server Example Application main file.
 *
 * @details This example demonstrates a CoAP server application that provides resources to control BSP_LED_3
 *          via CoAP messages. It can be controlled by a board with related Simple CoAP Server application.
 */

#include <stdint.h>

#include "app_timer.h"
#include "bsp_thread.h"
#include "nrf_log_ctrl.h"
#include "nrf_log.h"
#include "nrf_log_default_backends.h"

#include "thread_coap_utils.h"
#include "thread_utils.h"

#include <openthread/openthread.h>

void ot_receive_handler(otMessage *aMessage, void *aContext)
{
    
      NRF_LOG_INFO("packet received");
}

void change_rec(void)
{
       
        otIp6SetReceiveFilterEnabled(thread_ot_instance_get(), true);
	otIp6SetReceiveCallback(thread_ot_instance_get(),ot_receive_handler, NULL);
}



/***************************************************************************************************
 * @section Buttons
 **************************************************************************************************/

static void bsp_event_handler(bsp_event_t event)
{
    switch(event)
    {

         case BSP_EVENT_KEY_2:
            change_rec();
            break;

        case BSP_EVENT_KEY_3:
            thread_coap_utils_provisioning_enable(true);
            break;

        default:
            return;
    }
}

/***************************************************************************************************
 * @section Callbacks
 **************************************************************************************************/

static void thread_state_changed_callback(uint32_t flags, void * p_context)
{
    if (flags & OT_CHANGED_THREAD_ROLE)
    {
        switch (otThreadGetDeviceRole(p_context))
        {
            case OT_DEVICE_ROLE_CHILD:
            case OT_DEVICE_ROLE_ROUTER:
            case OT_DEVICE_ROLE_LEADER:
                break;

            case OT_DEVICE_ROLE_DISABLED:
            case OT_DEVICE_ROLE_DETACHED:
            default:
                thread_coap_utils_provisioning_enable(false);
                break;
        }
    }
    NRF_LOG_INFO("State changed! Flags: 0x%08x Current role: %d\r\n",
                 flags,
                 otThreadGetDeviceRole(p_context));

}

/***************************************************************************************************
 * @section Initialization
 **************************************************************************************************/

/**@brief Function for initializing the Application Timer Module.
 */
static void timer_init(void)
{
    uint32_t error_code = app_timer_init();
    APP_ERROR_CHECK(error_code);
}


/**@brief Function for initializing the nrf log module.
 */
static void log_init(void)
{
    ret_code_t err_code = NRF_LOG_INIT(NULL);
    APP_ERROR_CHECK(err_code);

    NRF_LOG_DEFAULT_BACKENDS_INIT();
}


/**@brief Function for initializing the Thread Board Support Package.
 */
static void thread_bsp_init(void)
{
    uint32_t error_code = bsp_init(BSP_INIT_LED | BSP_INIT_BUTTONS, bsp_event_handler);
    APP_ERROR_CHECK(error_code);

    error_code = bsp_thread_init(thread_ot_instance_get());
    APP_ERROR_CHECK(error_code);
}


/**@brief Function for initializing the Thread Stack.
 */
static void thread_instance_init(void)
{
    thread_configuration_t thread_configuration =
    {
        .role                  = RX_ON_WHEN_IDLE,
        .autocommissioning     = true,
        .poll_period           = 2500,
        .default_child_timeout = 10,
    };

    thread_init(&thread_configuration);
    thread_cli_init();
    thread_state_changed_callback_set(thread_state_changed_callback);
}


/**@brief Function for initializing the Constrained Application Protocol Module.
 */
static void thread_coap_init(void)
{
    thread_coap_configuration_t thread_coap_configuration =
    {
        .coap_server_enabled               = true,
        .coap_client_enabled               = false,
        .coap_cloud_enabled                = false,
        .configurable_led_blinking_enabled = false,
    };

    thread_coap_utils_init(&thread_coap_configuration);
}

/***************************************************************************************************
 * @section Main
 **************************************************************************************************/

int main(int argc, char * argv[])
{
      
  
    log_init();
    timer_init();

    // Initialize Thread CoAP utils.
    thread_coap_utils_led_timer_init();
    thread_coap_utils_provisioning_timer_init();
    thread_coap_utils_led_timer_start();

    // Initialize the Thread stack.
    thread_instance_init();
    thread_coap_init();
    thread_bsp_init();

    while (true)
    {
        thread_process();
    if (NRF_LOG_PROCESS() == false)
        {
            thread_sleep();

        }
    }
}

/**
 *@}
 **/
```

**Comment by jwhui** [comment] 2019-02-23 05:54
I believe this is due to your IPv6 packet not being formatted properly at the sender, as mentioned in #3600.

**Comment by testter2** [comment] 2019-02-23 06:04
> 
> 
> I believe this is due to your IPv6 packet not being formatted properly at the sender, as mentioned in #3600.

this the address i'm using now
header[2]=(0xADDEFD);
header[3]=(0xEFBE);
header[4]=(0xFF000000);
header[5]=(0x6400FE);

and that's the addresses i'm getting from ipaddr command
fdde:ad00:beef:0:0:ff:fe00:fc00
fdde:ad00:beef:0:0:ff:fe00:6400 (i'm using that address)
fe80:0:0:0:e036:1ed7:3316:76dd
fdde:ad00:beef:0:660b:9537:5373:7a2e

**Comment by testter2** [comment] 2019-02-23 06:14
this's the packet i'm trying to send 
start of header as : version,traffic class,flow label,payload length,next header,hop limit
source address : fdde:ad00:beef:0:0:ff:fe00:6400
destination address : FF030000 : : 1
data : aData [20]={1,0,2,3,1,0,2,3,1,0,2,3,1,0,2,3,1,0,2,3};

**Comment by jwhui** [comment] 2019-03-04 20:35
Duplicate of #3600.

**Closed by jwhui** 2019-03-04 20:35 UTC
Labels: api: user, question
