### ISSUE TITLE
efr32 CSMA done twice?

### ISSUE THREAD

**Issue by tomas-c** [openthread/openthread#2379] opened 2017-11-30 16:33 UTC
It seems that both the radio and OpenThread perform CSMA.

In efr32 radio.c function otPlatRadioTransmit
```
RAIL_CsmaConfig_t csmaConfig = RAIL_CSMA_CONFIG_802_15_4_2003_2p4_GHz_OQPSK_CSMA;
...
railTxStatus = RAIL_TxStartWithOptions(aFrame->mChannel, &txOption, RAIL_CcaCsma, &csmaConfig);
```

RAIL_CSMA_CONFIG_802_15_4_2003_2p4_GHz_OQPSK_CSMA is

```
/**
 * @def RAIL_CSMA_CONFIG_802_15_4_2003_2p4_GHz_OQPSK_CSMA
 * @brief RAIL_CsmaConfig_t initializer configuring CSMA per 802.15.4-2003
 * on 2.4 GHz OSPSK, commonly used by ZigBee.
 */
#define RAIL_CSMA_CONFIG_802_15_4_2003_2p4_GHz_OQPSK_CSMA {                    \
    /* CSMA per 802.15.4-2003 on 2.4 GHz OSPSK, commonly used by ZigBee     */ \
    /* csmaMinBoExp */ 3,   /* 2^3-1 for 0..7 backoffs on 1st try           */ \
    /* csmaMaxBoExp */ 5,   /* 2^5-1 for 0..31 backoffs on 3rd+ tries       */ \
    /* csmaTries    */ 5,   /* 5 tries overall (4 re-tries)                 */ \
    /* ccaThreshold */ -75, /* 10 dB above sensitivity                      */ \
    /* ccaBackoff   */ 320, /* 20 symbols at 16 us/symbol                   */ \
    /* ccaDuration  */ 128, /* 8 symbols at 16 us/symbol                    */ \
    /* csmaTimeout  */ 0,   /* no timeout                                   */ \
}
```

so SiLabs Rail is set to use CSMA.

Now if we look into MAC layer, we see that before transmitting it calls `RadioSupportsCsmaBackoff()` and if it returns false - performs its own CSMA. In efr32 radio.c function, otPlatRadioGetCaps doesn't set OT_RADIO_CAPS_TRANSMIT_RETRIES or OT_RADIO_CAPS_CSMA_BACKOFF bits so this is precisely what happens.

**Comment by xiaom-GitHub** [comment] 2017-12-01 00:41
Thanks for helping test and debug the root cause！sorry to bring this issue. Just as you mentioned, please supplement OT_RADIO_CAPS_CSMA_BACKOFF & OT_RADIO_CAPS_TRANSMIT_RETRIES cap in otPlatRadioGetCaps() to see if the issue will be fixed. If so, would you mind to submit a PR for this bug? Thanks!

**Comment by tomas-c** [comment] 2017-12-04 15:05
Thanks, Xiaom. Will do once I get #2372 sorted. Thought just mention now before someone else starts looking.

**Comment by jwhui** [comment] 2017-12-06 21:44
I've addressed this issue as part of the transition to RAIL 2.x in #2401.

**Closed** 2018-01-09 17:47 UTC
Labels: P4, bug, platform: efr32
