### ISSUE TITLE
 Nordic's nRF5340 DK support Request

### ISSUE THREAD

**Issue by lboue** [openthread/openthread#8268] opened 2022-10-11 15:15 UTC
Hello,

Could you add support for  Nordic's nRF5340 DK as Network Co-Processor (NCP)?

Regards

**Comment by jwhui** [comment] 2022-10-13 21:44
Closing as duplicate of https://github.com/openthread/ot-nrf528xx/issues/426

**Closed by jwhui** 2022-10-13 21:44 UTC
Labels: duplicate
